export const MY_EXPERIENCES = [
  {
    title: "Frontend Developer",
    company: "PT. Samala Serasi Unggul - Rumah Siap Kerja",
    employmentType: "Full-time",
    date: "May 2021 - Sept 2024",
    inYears: "3 years 5 months",
    location: "Jakarta, Indonesia",
    locationType: "Remote",
    summary:
      "Led frontend development for Rumah Siap Kerja's back-office system, focusing on user experience enhancement and performance optimization.",
    responsibilities: [
      "Developed and maintained the back-office system, ensuring seamless user experience and optimal performance.",
      "Collaborated with cross-functional teams to identify and resolve software bugs and implement enhancements.",
      "Optimized front-end code for faster load times and improved overall performance.",
      "Built a design system and led the migration from Vue.js to React.js from scratch.",
      "Ensured the back-office system remained bug-free and maintained high performance.",
    ],
    techStack: [
      "HTML",
      "SCSS",
      "TypeScript",
      "JavaScript",
      "React.js",
      "MaterialUI",
      "React Hook Form",
      "TanStack Query (React Query)",
      "Vue.js",
      "Nuxt.js",
      "Vuetify.js",
      "Vuelidate",
      "Responsive Design",
      "Nest.js",
      "TypeORM",
      "MySQL",
    ],
  },
  {
    title: "Frontend Developer",
    company: "PT. BIT - Barito Technologies Group",
    employmentType: "Full-time",
    date: "Jun 2019 - Sept 2021",
    inYears: "2 years 4 months",
    location: "Jakarta, Indonesia",
    locationType: "On-site",
    summary: `Developed back-office applications for managing activities and leads, focusing on PRU-Hub platform.`,
    responsibilities: [
      "Developed and maintained the PRU-Hub platform, ensuring seamless user experience.",
      "Implemented responsive design principles to ensure optimal user experience across various devices.",
      "Collaborated with cross-functional teams to identify and resolve software bugs and enhancements.",
    ],
    techStack: [
      "HTML",
      "SCSS",
      "TypeScript",
      "JavaScript",
      "React.js",
      "Angular.js",
      "Ionic",
      "Responsive Design",
      "Java",
      "Spring Boot",
      "PostgreSQL",
    ],
  },
  {
    title: "Full Stack Developer",
    company: "Blenderbox, Inc.",
    employmentType: "Contract",
    date: "Nov 2018 - Jun 2019",
    inYears: "8 months",
    location: "Bandung, Indonesia",
    locationType: "On-site",
    summary: `At Blenderbox, my responsibilities included identifying and ensuring reliable and bug-free software delivery. My work supported system development processes, showcasing my attention to quality and problem-solving abilities in a full-stack environment.`,
    responsibilities: [
      "Identified, analyzed, and resolved issues, errors, and bugs.",
      "Conducted program testing and debugging to ensure a bug-free application.",
      "create new features according to client requests",
    ],
    techStack: [
      "HTML",
      "SCSS",
      "TypeScript",
      "JavaScript",
      "PHP",
      "MySQL",
      "Responsive Design",
    ],
  },
  {
    title: "Junior Full Stack Developer",
    company: "PT. Navcore Nextology",
    employmentType: "Contract",
    date: "Feb 2018 - Sept 2018",
    inYears: "8 months",
    location: "Jakarta, Indonesia",
    locationType: "On-site",
    summary: `I'm contributed to the Distributed Channel Network (DCN) project, which facilitated flight ticket reservations and Hajj/Umrah travel.`,
    responsibilities: [
      "Developed and maintained the DCN project.",
      "Integrated with Nexigo API (internal framework).",
      "Collaborated with cross-functional teams to identify and resolve software bugs and enhancements.",
    ],
    techStack: [
      "HTML",
      "SCSS",
      "JavaScript",
      "JQuery",
      "Kendo Grid",
      "Responsive Design",
      "Nexigo API (internal framework)",
      "PostgreSQL",
    ],
  },
];

export const MY_EDUCATION_AND_CERTIFICATION = [
  {
    provider: "Makers Institute",
    description: "Full-stack Academy Bootcamp",
    date: "Nov 2017 - Jan 2018",
    credentialLink:
      "https://drive.google.com/file/d/1S__gyEZBc0dnQqsEPciL3w_jehMuvdwk/view",
  },
  {
    provider: "Freecodecamp.org",
    description: "Responsive Web Design",
    date: "Jul 2021",
    credentialLink:
      "https://www.freecodecamp.org/certification/wismannur/responsive-web-design",
  },
];

export const MY_USES = [
  `Monitor Lenovo G34W-30 34" UltraWide 1440p 170Hz Curved 2024`,
  "Apple Mac Mini M1 Chip with 8-Core CPU 512GB 2020",
  "Apple Magic Mouse 2 - White",
  "Fantech Mint Edition Agile MP904 Mousepad Gaming",
  "Logitech Pebble Keys2 K380s Keyboard Wireless Bluetooth Multi Device - Tonal Graphite",
  "Logitech Webcam C270 HD",
  "Workdesign - Tota Natu TT160 Electric Workbench with Adjustable Lift Up - Brown Walnut",
  "Deli Office Chair / Mesh Work Chair with Headrest E492X - Black",
  "JETE 09 Bluetooth Earphone Sport Extra Bass IPX4",
];
