import type { AtsTargetCompany } from "./types";

export const PRESET_ATS_COMPANIES: AtsTargetCompany[] = [
  // Ashby Tier-1
  {
    id: "preset-linear",
    name: "Linear",
    platform: "ashby",
    slug: "linear",
    websiteUrl: "https://linear.app",
    logoUrl: "https://linear.app/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-supabase",
    name: "Supabase",
    platform: "ashby",
    slug: "supabase",
    websiteUrl: "https://supabase.com",
    logoUrl: "https://supabase.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-cursor",
    name: "Cursor",
    platform: "ashby",
    slug: "cursor",
    websiteUrl: "https://cursor.com",
    logoUrl: "https://cursor.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-openai",
    name: "OpenAI",
    platform: "ashby",
    slug: "openai",
    websiteUrl: "https://openai.com",
    logoUrl: "https://openai.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-ramp",
    name: "Ramp",
    platform: "ashby",
    slug: "ramp",
    websiteUrl: "https://ramp.com",
    logoUrl: "https://ramp.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-replit",
    name: "Replit",
    platform: "ashby",
    slug: "replit",
    websiteUrl: "https://replit.com",
    logoUrl: "https://replit.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-sentry",
    name: "Sentry",
    platform: "ashby",
    slug: "sentry",
    websiteUrl: "https://sentry.io",
    logoUrl: "https://sentry.io/favicon.ico",
    isActive: true,
    isCustom: false,
  },

  // Greenhouse Tier-1
  {
    id: "preset-gitlab",
    name: "GitLab",
    platform: "greenhouse",
    slug: "gitlab",
    websiteUrl: "https://gitlab.com",
    logoUrl: "https://gitlab.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-vercel",
    name: "Vercel",
    platform: "greenhouse",
    slug: "vercel",
    websiteUrl: "https://vercel.com",
    logoUrl: "https://vercel.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-figma",
    name: "Figma",
    platform: "greenhouse",
    slug: "figma",
    websiteUrl: "https://figma.com",
    logoUrl: "https://figma.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-stripe",
    name: "Stripe",
    platform: "greenhouse",
    slug: "stripe",
    websiteUrl: "https://stripe.com",
    logoUrl: "https://stripe.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-cloudflare",
    name: "Cloudflare",
    platform: "greenhouse",
    slug: "cloudflare",
    websiteUrl: "https://cloudflare.com",
    logoUrl: "https://cloudflare.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
  {
    id: "preset-airbnb",
    name: "Airbnb",
    platform: "greenhouse",
    slug: "airbnb",
    websiteUrl: "https://airbnb.com",
    logoUrl: "https://airbnb.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },

  // Lever Tier-1
  {
    id: "preset-spotify",
    name: "Spotify",
    platform: "lever",
    slug: "spotify",
    websiteUrl: "https://spotify.com",
    logoUrl: "https://spotify.com/favicon.ico",
    isActive: true,
    isCustom: false,
  },
];
